# Generated by Django 5.2.2 on 2025-06-10 05:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("course_id", models.UUIDField(db_index=True)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(db_index=True)),
                ("deadline", models.DateTimeField(db_index=True)),
                ("max_score", models.FloatField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
        ),
    ]
