# Generated by Django 5.2.2 on 2025-06-10 05:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assignment_id", models.UUIDField(db_index=True)),
                ("student_id", models.UUIDField(db_index=True)),
                ("content", models.TextField(blank=True, db_index=True, null=True)),
                ("file", models.BinaryField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(db_index=True)),
                ("score", models.FloatField(blank=True, db_index=True, null=True)),
                ("feedback", models.TextField(blank=True, db_index=True, null=True)),
            ],
        ),
    ]
