# Generated by Django 5.2.2 on 2025-06-10 05:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "student_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "hemis_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True, unique=True
                    ),
                ),
                ("full_name", models.CharField(db_index=True, max_length=200)),
                ("password_hash", models.CharField(max_length=255)),
                ("created_by", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
        ),
    ]
